### ISSUE TITLE
fix: deploy still fails — coverage.provider inferred as string after UserConfig removal

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/allotmint#2949]
## Problem

After merging #2948, the deploy pipeline still fails at "Build frontend":

```
vite.config.ts(7,29): error TS2769: No overload matches this call.
  The types of 'test.coverage.provider' are incompatible between these types.
    Type 'string' is not assignable to type '"v8" | "istanbul" | "custom" | undefined'.
```

## Root Cause

Removing the explicit `UserConfig` type annotation in #2948 caused TypeScript to widen `coverage.provider: 'v8'` from the string literal `'v8'` to the broader `string` type. `defineConfig` from `vitest/config` expects the literal union `"v8" | "istanbul" | "custom"`, so the inferred `string` no longer satisfies it.

## Fix

Add `as const` to the `provider` value in `frontend/vite.config.ts`:

```ts
provider: 'v8' as const,
```
