### ISSUE TITLE
fix: AuthContext.tsx build error — setUser type too wide after #2774 refactor

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/allotmint#2776]
## Problem

After merging #2774, the deploy workflow fails at `tsc -b`:

```
src/AuthContext.tsx(13,27): error TS2345: Argument of type 'SetStateAction<StoredUserProfile | null>'
is not assignable to parameter of type 'StoredUserProfile | null'.
```

`AuthContextValue.setUser` is typed as `(u: UserProfile | null) => void` in `contexts/auth.ts`. The refactored `AuthContext.tsx` used `Parameters<typeof setUserState>[0]` which resolves to `SetStateAction<T>` — a union that includes updater functions `(prev: T) => T`. TypeScript rejects this as incompatible with the narrower interface type.

## Fix

Restore the explicit `UserProfile | null` annotation on the `setUser` callback parameter, and restore the explicit `useState<UserProfile | null>` generic so inference is tight.

## Acceptance criteria

- [ ] `tsc -b` passes with zero errors
- [ ] `setUser` in `AuthProvider` accepts only `UserProfile | null`, not updater functions
